In [38]:
import pandas as pd
import ast

Gathering Data

In [39]:
df = pd.read_csv('synthetic_data_4.csv')

Assesing Data

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306000 entries, 0 to 305999
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               290602 non-null  float64
 1   years_experience  290703 non-null  float64
 2   education_level   290662 non-null  object
 3   major             290671 non-null  object
 4   skill_score       290879 non-null  float64
 5   job               290653 non-null  object
 6   skills            290796 non-null  object
 7   certifications    290620 non-null  object
 8   projects          290710 non-null  object
 9   summary           290703 non-null  object
 10  experience_desc   290480 non-null  object
dtypes: float64(3), object(8)
memory usage: 25.7+ MB

In [41]:
df.isna().sum()

age                 15398
years_experience    15297
education_level     15338
major               15329
skill_score         15121
job                 15347
skills              15204
certifications      15380
projects            15290
summary             15297
experience_desc     15520
dtype: int64

In [42]:
print("Jumlah duplikasi: ", df.duplicated().sum())

Jumlah duplikasi:  5884

In [43]:
df.describe()

                 age  years_experience    skill_score
count  290602.000000     290703.000000  290879.000000
mean       27.274693          5.724944      65.967521
std         4.999518          4.959387      19.658948
min         8.909209          0.000000       0.000000
25%        24.250000          1.020571      52.419820
50%        27.058429          4.995268      66.309556
75%        29.890545          9.067385      79.829195
max       127.445214         32.016107     200.000000

Cleaning Data

In [44]:
df = df.drop_duplicates()
df = df.dropna(subset=['job'])

In [45]:
print("Shape setelah drop duplikat:", df.shape)

Shape setelah drop duplikat: (285045, 11)

In [46]:
df['age'] = df['age'].clip(lower=18, upper=60)
df['skill_score'] = df['skill_score'].clip(lower=0, upper=100)

In [47]:
def parse_list(x):
    if pd.isna(x): return []
    try: return ast.literal_eval(x)
    except: return []

for col in ['skills', 'certifications', 'projects']:
    df[col] = df[col].apply(parse_list)

In [48]:
print("Tipe data skills sekarang:", type(df['skills'].iloc[0]))

Tipe data skills sekarang: <class 'list'>

In [49]:
df['age'] = df['age'].fillna(df['age'].median())
df['years_experience'] = df['years_experience'].fillna(df['years_experience'].median())
df['skill_score'] = df['skill_score'].fillna(df['skill_score'].median())

for col in ['education_level', 'major', 'summary', 'experience_desc']:
    df[col] = df[col].fillna('unknown')

In [50]:
print("Sisa missing value per kolom:\n", df.isna().sum())

Sisa missing value per kolom:
 age                 0
years_experience    0
education_level     0
major               0
skill_score         0
job                 0
skills              0
certifications      0
projects            0
summary             0
experience_desc     0
dtype: int64

In [51]:
for col in ['job', 'education_level', 'major']:
    df[col] = df[col].astype(str).str.lower().str.strip()

print("Sisa missing value:\n", df.isna().sum())
print("\nShape setelah cleaning:", df.shape)

Sisa missing value:
 age                 0
years_experience    0
education_level     0
major               0
skill_score         0
job                 0
skills              0
certifications      0
projects            0
summary             0
experience_desc     0
dtype: int64

Shape setelah cleaning: (285045, 11)

In [54]:
df = df[~df.astype(str).duplicated()]

In [56]:
print("hasil cek akhir")
print("Shape final:", df.shape)
print("Total Duplikat:", df.astype(str).duplicated().sum())
print("Total Missing Value:", df.isna().sum().sum())

hasil cek akhir
Shape final: (285044, 11)
Total Duplikat: 0
Total Missing Value: 0

In [58]:
print("1. Cek Info dan Tipe Data")
df.info()

print("\n2. Cek Sisa Data Kosong dan Duplikat")
print("Sisa data kosong:", df.isna().sum().sum())
print("Sisa data duplikat:", df.astype(str).duplicated().sum())

print("\n3. Cek Rentang Nilai Umur dan Skor")
print("Umur terkecil dan terbesar:", df['age'].min(), "-", df['age'].max())
print("Skor terkecil dan terbesar:", df['skill_score'].min(), "-", df['skill_score'].max())

print("\n4. Lihat 3 Baris Teratas")
display(df.head(3))

1. Cek Info dan Tipe Data
<class 'pandas.core.frame.DataFrame'>
Index: 285044 entries, 0 to 305946
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   age               285044 non-null  float64
 1   years_experience  285044 non-null  float64
 2   education_level   285044 non-null  object
 3   major             285044 non-null  object
 4   skill_score       285044 non-null  float64
 5   job               285044 non-null  object
 6   skills            285044 non-null  object
 7   certifications    285044 non-null  object
 8   projects          285044 non-null  object
 9   summary           285044 non-null  object
 10  experience_desc   285044 non-null  object
dtypes: float64(3), object(8)
memory usage: 26.1+ MB

2. Cek Sisa Data Kosong dan Duplikat
Sisa data kosong: 0
Sisa data duplikat: 0

3. Cek Rentang Nilai Umur dan Skor
Umur terkecil dan terbesar: 18.0 - 60.0
Skor terkecil dan terbesar: 0.0 - 100.0

4. Lihat 3 Baris Teratas

,age,years_experience,education_level,major,skill_score,job,skills,certifications,projects,summary,experience_desc
0,27.214469,8.299930,master,arts,64.399443,teacher,[Teaching],[],[teaching curriculum],"Experienced teacher with 7 years background, p...","Involved in teaching curriculum, delivering qu..."
1,27.000514,4.407777,master,arts,79.620950,teacher,[Teaching],[],"[mentorship program, workshop, teaching curric...",I am a master graduate in arts with 4 years of...,Involved in mentorship program; workshop; teac...
2,30.875727,8.817801,bachelor,business,44.478979,data_analyst,[Excel],[Tableau],"[dashboard project, ETL pipeline, sales predic...",With a degree in business (bachelor) and 8 yea...,Key projects: dashboard project; ETL pipeline;...

In [60]:
df.to_csv('dataset_after_wrangling.csv', index=False)